# Generated by Django 4.2.7 on 2023-12-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_action_tache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='nom',
            new_name='name',
        ),
    ]
