# Generated by Django 4.2.7 on 2023-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelant',
            name='phone',
            field=models.CharField(default='699913839', max_length=20, verbose_name='phone'),
        ),
    ]
