# Generated by Django 4.2.7 on 2023-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0007_alter_technicien_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='nom',
        ),
        migrations.AddField(
            model_name='technicien',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
